//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSuperMartket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddToCart
    {
        public int AddToCart_id { get; set; }
        public Nullable<int> user_id_ { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public int category_ID { get; set; }
        public Nullable<int> brand_ID { get; set; }
        public string Product_name { get; set; }
        public string Product_disc { get; set; }
        public Nullable<int> Product_code { get; set; }
        public int whole_sale_price { get; set; }
        public int retail_price { get; set; }
        public Nullable<int> stock { get; set; }
        public string imgPath { get; set; }
        public System.DateTime create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> makeorder { get; set; }
    }
}
