//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSuperMartket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int Discount_ID { get; set; }
        public string Discount_Code { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Brand_Code { get; set; }
        public Nullable<int> Upto_percent { get; set; }
        public Nullable<int> Upto_RS { get; set; }
        public Nullable<bool> Get_One_By_One { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
    }
}
