//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSuperMartket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderID { get; set; }
        public Nullable<int> venderid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> productsid { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<long> productsAmount { get; set; }
        public string prductsname { get; set; }
        public string categoryname { get; set; }
        public string venderoname { get; set; }
        public Nullable<int> customerid { get; set; }
        public string customernam { get; set; }
        public Nullable<bool> isDispatch { get; set; }
    }
}
