//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSuperMartket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class statement
    {
        public int Stmt_ID { get; set; }
        public Nullable<int> Pay_Type_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Create_AT { get; set; }
        public Nullable<System.DateTime> Update_At { get; set; }
        public Nullable<bool> is_Active { get; set; }
    
        public virtual Payement_Type Payement_Type { get; set; }
        public virtual Product Product { get; set; }
        public virtual user user { get; set; }
    }
}
